stages:
  - checkConvention
  - DeployTest
checkConvention:
  stage: checkConvention
  image: composer
  script:
    - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar && curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar
    - mv phpcs.phar /usr/local/bin/phpcs && chmod +x /usr/local/bin/phpcs
    - mv phpcbf.phar /usr/local/bin/phpcbf && chmod +x /usr/local/bin/phpcbf
    - phpcs --standard=PSR2 --config-set show_warnings 0 app/
DeployTest:
  stage: DeployTest
  image: alpine
  only:
    - develop
  script:
    - apk update && apk add openssh
    - apk add rsync
    - mkdir -p ~/.ssh
    - echo "$TEST_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H '52.76.107.8'  >> ~/.ssh/known_hosts
    - echo "$TEST_ENV" > .env
    - rsync --progress -avzh --exclude='.git' -e "ssh -i ~/.ssh/id_rsa " --rsync-path="sudo rsync" . ec2-user@52.76.107.8:/var/www/dev
    - ssh -i ~/.ssh/id_rsa ec2-user@52.76.107.8 "
      cd /var/www/dev
      && sudo chmod -R 777 storage/app/
      && composer install
      && composer dump-autoload
      && sudo php artisan migrate
      && sudo php artisan cache:clear
      && sudo php artisan route:clear
      && sudo php artisan config:clear
      && sudo php artisan storage:link
      && npm install
      && sudo npm run dev"

