<?php

namespace App\Repositories;

use App\Models\MemberRequest;

class MemberRequestsRepository extends Repository
{
    public function getModel()
    {
        return new MemberRequest();
    }

    public function getWithClub(int $id)
    {
        return $this->getModel()
            ->with('members')
            ->get();
    }

    public function getById($id, array $options = [])
    {
        return parent::getById($id, $options); // TODO: Change the autogenerated stub
    }
}
