<?php

namespace App\Repositories;

use App\Models\MemberRequest;

class MemberRequestsRepository extends Repository
{
    public function getModel()
    {
        return new MemberRequest();
    }

    public function getWithClub(int $id)
    {
        return $this->getModel()
            ->with('members')
            ->where('club_id', $id)
            ->get();
    }

    public function getById($id, array $options = [])
    {
        return parent::getById($id, $options); // TODO: Change the autogenerated stub
    }

    public function getMemberRequest($userId)
    {
        return $this->getModel()
            ->where('member_id', $userId)
            ->where('status', MemberRequest::NEW)
            ->get();
    }

    public function getRequestWithManager($userId)
    {
        return $this->getModel()
            ->select('member_requests.*')
            ->with('members')
            ->with('sports_disciplines')
            ->join('clubs', 'clubs.id', '=', 'member_requests.club_id')
            ->where('clubs.manager_id', $userId)
            ->where('member_requests.status', MemberRequest::NEW)
            ->get();
    }
}
